dmhy:
  - 雪飘 Steins Gate 简体
  - 轻之国度 遙的接球 720P MP4
  - 喵萌茶会字幕组 来玩游戏吧 简体
  - YMDR 奴隶魔术 BIG5 MP4
  - 澄空学园 ISLAND MP4 720P
  - 澄空 happy sugar life MP4 720P

nyaa:
  - Ohys-Raws Happy Sugar Life
  - Ohys-Raws Isekai Maou to Shoukan Shoujo no Dorei Majutsu
