dmhy:
  - 雪飘 Steins Gate 简体
  - 轻之国度 遙的接球 720P MP4
  - 喵萌茶会 来玩游戏吧 简体
  - YMDR 奴隶魔术 BIG5 MP4
  - 澄空 ISLAND MP4 720P
  - 澄空 happy sugar life MP4 720P
  - 喵萌茶会 高分少女 720P MP4 简体
  - 动漫国 轻羽飞扬 720P 简体 MP4

nyaa:
  - Ohys-Raws Happy Sugar Life
  - Ohys-Raws Isekai Maou to Shoukan Shoujo no Dorei Majutsu
