dmhy:
# 2018-07
  - 雪飘 Steins Gate 简体
  - 轻之国度 遙的接球 720P MP4
  - 喵萌茶会 来玩游戏吧 简体
  - YMDR 奴隶魔术 BIG5 MP4
  - 澄空 ISLAND MP4 720P
  - 澄空 happy sugar life MP4 720P
  - 喵萌茶会 高分少女 720P MP4 简体
  - 动漫国 轻羽飞扬 720P 简体 MP4
  - YMDR overlord III MP4
  - 悠哈 天狼 CHS 720P
  - YMDR 工作細胞 MP4
  - 桜都 杀戮天使 GB 720P
  - 轻之国度 春原庄的管理员小姐
  - 极影 千緒的通學路 GB 1080P
# 2018-10
  - 轻之国度 哥布林杀手
  - 千夏字幕组 我家的女仆太烦人了
# 2019-01
  - 喵萌奶茶屋 荒野的寿飞行队 简体
  - 喵萌奶茶屋 Girly Air Force 简体
  - 桜都字幕組 家有女友 简体
  - 轻之国度 Endro

nyaa:
# 2018-07
  - Ohys-Raws Happy Sugar Life
  - Ohys-Raws Isekai Maou to Shoukan Shoujo no Dorei Majutsu
# 2018-10
  - Ohys-Raws Conception
  - 电光超人古立特
  - Ohys-Raws SSSS.Gridman
