dmhy:
# 2019-01
  - 桜 狂赌 XX GB|CHS
# 2019-04
  - 喵萌奶茶屋 Fairy Gone 简体 720
  - 桜都 信长老师的幼妻 GB
  - 桜都 一拳超人 第2季 GB
  - Nande Koko ni Sensei ga 1080P 繁体外挂字幕
  - 轻之国度 贤惠幼妻
  - 澄空学园 YU-NO

nyaa:
  - HorribleSubs Joshikausei
