dmhy:
# 2019-04
  - 喵萌奶茶屋 Fairy Gone 简体 720
  - 桜都 信长老师的幼妻 GB
  - 桜都 一拳超人 第2季 GB
  - Nande Koko ni Sensei ga 1080P 繁体外挂字幕
  - 轻之国度 贤惠幼妻
  - 澄空学园 YU-NO
# 2019-07
  # B站看不了的
  - 满月之战 简日双语
  - LoliHouse 为了女儿，我说不定连魔王都能干掉。
  - MMSUB 异世界超能魔术师
  # B站能看的
  - 喵萌奶茶屋 你遭难了吗 简体
  - 喵萌奶茶屋 魔术学姐 简体
  - 喵萌奶茶屋 平凡职业成就世界最强 简体
  - 喵萌奶茶屋 女高中生的无用日常 简体
  - 轻之国度 肌肉少女：哑铃，能举多少公斤？
  - 漫猫 魔王大人
  - 幻樱 Grace note GB
  - BYYM 普通攻擊 HEVC
  - 喵萌奶茶屋 街角魔族 1080p 简体
  - MMSUB 某科学的一方通行
  - BYYM 在地下城尋求邂逅是否搞錯了什麼 HEVC
  - 星空字幕组 炎炎消防队 MP4
  - 千夏字幕组 擅长捉弄人的高木同学2 简体
  - 动漫国 彼方的阿斯特拉 简体 1080P

nyaa:
# 2019-04
  - HorribleSubs Joshikausei
